webimblaze-check/Models/Recipe.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace webimblaze_check.Models
{
    public class Recipe
    {
        public int ID { get; set; }

        [Display(Name = "Date")]
        [DataType(DataType.DateTime)]
        public DateTime CreateDate { get; set; }

        [Display(Name = "Delay Seconds")]
        [Range(0, 75, ErrorMessage = "Delay must be between 0 and 75 seconds")]
        public int DelaySeconds { get; set; }

        [StringLength(60, MinimumLength = 3)]
        [Required(ErrorMessage = "Recipe Name is required")]
        [RegularExpression(@"^[A-Z]+[a-zA-Z0-9'\-\s]*$", ErrorMessage = "Recipe Name should have no special characters other than a dash")]
        public string Name { get; set; }

        [StringLength(24, MinimumLength = 2)]
        [Required(ErrorMessage = "Recipe Name is required")]
        [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$", ErrorMessage = "Cuisine can not have special characters or numbers")]
        public string Cuisine { get; set; }

        [Range(1, 12, ErrorMessage = "Free edition supports 1 to 12 servings, for more options please purchase the PRO edition")]
        public decimal Serves { get; set; }

        public bool Vegetarian { get; set; }
    }
}

webimblaze-check/Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using webimblaze_check.Models;

namespace webimblaze_check.Controllers
{
    public class RecipesController : Controller
    {
        private readonly webimblazecheckContext _context;

        public RecipesController(webimblazecheckContext context)
        {
            _context = context;    
        }

        // GET: Recipes
        public async Task<IActionResult> Index(string recipeCuisine, string searchString)
        {
            // Clear out old recipes that we are bored with
            _context.Recipe.RemoveRange(_context.Recipe.Where(x => x.CreateDate < DateTime.Now.AddMinutes(-6)));
            await _context.SaveChangesAsync();


            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from m in _context.Recipe
                                            orderby m.Cuisine
                                            select m.Cuisine;

            var recipes = from m in _context.Recipe
                          where (m.CreateDate < DateTime.Now.AddSeconds(-m.DelaySeconds))
                          select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                recipes = recipes.Where(s => s.Name.Contains(searchString));
            }

            if (!String.IsNullOrEmpty(recipeCuisine))
            {
                recipes = recipes.Where(x => x.Cuisine == recipeCuisine);
            }

            var recipeCusineVM = new RecipeCuisineViewModel();
            recipeCusineVM.cuisines = new SelectList(await genreQuery.Distinct().ToListAsync());
            recipeCusineVM.recipes = await recipes.ToListAsync();

            return View(recipeCusineVM);
        }

        [HttpPost]
        public string Index(string searchString, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + searchString;
        }

        // GET: Recipes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipe = await _context.Recipe
                .SingleOrDefaultAsync(m => m.ID == id);
            if (recipe == null)
            {
                return NotFound();
            }

            return View(recipe);
        }

        // GET: Recipes/Create
        public IActionResult Create()
        {
            Recipe newRecipe = new Recipe();
            newRecipe.Serves = 4; // Default
            newRecipe.DelaySeconds = 0; // Default

            return View(newRecipe);
        }

        // POST: Recipes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,CreateDate,DelaySeconds,Name,Cuisine,Serves,Vegetarian")] Recipe recipe)
        {
            if (ModelState.IsValid)
            {
                recipe.CreateDate = DateTime.Now;
                _context.Add(recipe);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(recipe);
        }

        // GET: Recipes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipe = await _context.Recipe.SingleOrDefaultAsync(m => m.ID == id);
            if (recipe == null)
            {
                return NotFound();
            }
            return View(recipe);
        }

        // POST: Recipes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,CreateDate,DelaySeconds,Name,Cuisine,Serves,Vegetarian")] Recipe recipe)
        {
            if (id != recipe.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                recipe.CreateDate = DateTime.Now;
                try
                {
                    _context.Update(recipe);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecipeExists(recipe.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(recipe);
        }

        // GET: Recipes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipe = await _context.Recipe
                .SingleOrDefaultAsync(m => m.ID == id);
            if (recipe == null)
            {
                return NotFound();
            }

            return View(recipe);
        }

        // POST: Recipes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var recipe = await _context.Recipe.SingleOrDefaultAsync(m => m.ID == id);
            _context.Recipe.Remove(recipe);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool RecipeExists(int id)
        {
            return _context.Recipe.Any(e => e.ID == id);
        }
    }
}

webimblaze-check/Views/Recipes/Create.cshtml
@model webimblaze_check.Models.Recipe

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Recipe</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Cuisine" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Cuisine" class="form-control" />
                <span asp-validation-for="Cuisine" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Serves" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Serves" class="form-control" />
                <span asp-validation-for="Serves" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <input asp-for="Vegetarian" />
                    <label asp-for="Vegetarian"></label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DelaySeconds" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DelaySeconds" class="form-control" />
                <span asp-validation-for="DelaySeconds" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

webimblaze-check/Views/Recipes/Delete.cshtml
@model webimblaze_check.Models.Recipe

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="ID" />
        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cuisine)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cuisine)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Serves)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Serves)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Vegetarian)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Vegetarian)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

webimblaze-check/Views/Recipes/Details.cshtml
@model webimblaze_check.Models.Recipe

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DelaySeconds)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DelaySeconds)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cuisine)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cuisine)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Serves)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Serves)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Vegetarian)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Vegetarian)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

webimblaze-check/Views/Recipes/Edit.cshtml
@model webimblaze_check.Models.Recipe

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Recipe</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Cuisine" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Cuisine" class="form-control" />
                <span asp-validation-for="Cuisine" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Serves" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Serves" class="form-control" />
                <span asp-validation-for="Serves" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <input asp-for="Vegetarian" />
                    <label asp-for="Vegetarian"></label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DelaySeconds" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DelaySeconds" class="form-control" />
                <span asp-validation-for="DelaySeconds" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

webimblaze-check/Views/Recipes/Index.cshtml
@model webimblaze_check.Models.RecipeCuisineViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Recipes" asp-action="Index" method="get">
    <p>
        <select asp-for="recipeCuisine" asp-items="Model.cuisines">
            <option value="">All</option>
        </select>

        Title: <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.recipes[0].CreateDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.recipes[0].DelaySeconds)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.recipes[0].Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.recipes[0].Cuisine)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.recipes[0].Serves)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.recipes[0].Vegetarian)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.recipes) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CreateDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DelaySeconds)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cuisine)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Serves)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vegetarian)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>